version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - .env
    volumes:
      - ./tickets:/app/tickets
      - ./output:/app/output
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - akatsuki-network
    restart: on-failure:3

networks:
  akatsuki-network:
    driver: bridge